### ISSUE TITLE
play-jongo for play 2.4.x

### ISSUE THREAD

**Issue by morellik** [alexanderjarvis/play-jongo#37]
Dear,

have you plan a release for the new play 2.4.1 version?

**Comment by effahmens** [comment]
I run into an issue when i tried to upgrade to 2.4.1. Any plans of upgrading

lay.api.UnexpectedException: Unexpected exception[ConfigurationException: Guice configuration errors:

1) Could not find a suitable constructor in uk.co.panaxiom.playjongo.JongoPlugin. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at uk.co.panaxiom.playjongo.JongoPlugin.class(JongoPlugin.java:9)
  while locating uk.co.panaxiom.playjongo.JongoPlugin

1 error]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:165) ~[play-server_2.11-2.4.2.jar:2.4.2]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:121) ~[play-server_2.11-2.4.2.jar:2.4.2]
	at scala.Option.map(Option.scala:146) ~[scala-library-2.11.6.jar:na]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:121) ~[play-server_2.11-2.4.2.jar:2.4.2]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:119) ~[play-server_2.11-2.4.2.jar:2.4.2]
Caused by: com.google.inject.ConfigurationException: Guice configuration errors:

1) Could not find a suitable constructor in uk.co.panaxiom.playjongo.JongoPlugin. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at uk.co.panaxiom.playjongo.JongoPlugin.class(JongoPlugin.java:9)
  while locating uk.co.panaxiom.playjongo.JongoPlugin

1 error
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1042) ~[guice-4.0.jar:na]
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1001) ~[guice-4.0.jar:na]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051) ~[guice-4.0.jar:na]
	at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:321) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.Plugins$$anonfun$loadPlugins$1.apply(Plugins.scala:89) ~[play_2.11-2.4.2.jar:2.4.2]

**Comment by magro** [comment]
There's a pull request for 2.4 compatibility, I'm just working on this (tests don't run, build path issues)...

**Comment by magro** [comment]
play-jongo-0.8.0-jongo1.2 is on its way to maven central, it's based on PR #36. Does this work for you?

The next step would probably be to provide a Module additionally / as replacement for the JongoPlugin, as plugins are deprecated with 2.4.

**Comment by morellik** [comment]
I tried to use play-jongo-0.8.0-jongo1.2 for a new 2.4 Play project.The first compilation works fine. Now I start to create models and I'll test more deep.

**Comment by morellik** [comment]
All seems to be working fine. Good work. Thanks

**Comment by magro** [comment]
great!
