### ISSUE TITLE
Syntax to use with Play 2.5.x

### ISSUE THREAD

**Issue by morellik** [alexanderjarvis/play-jongo#58]
If I use the play-jongo compiled by me and putted in lib directory, I'm able to use the module like:

 ```
 public static MongoCollection users() {
        return PlayJongo.getCollection("DocBox.users");
    }
```
If I try to put everything in build.sbt and changing the previous line like:

 ```
@Inject
    public static PlayJongo jongo;

    public static MongoCollection users() {
        return jongo.getCollection("DocBox.users");
    }
```

I receive a [NullPointerException: null] located at  _return jongo.getCollection("DocBox.users");_

Which is the right way to use the new version of play-jong?

Thanks

**Comment by morellik** [comment]
Seems that instantiating PlayJongo like below it's working:

`public static PlayJongo jongo = Play.current().injector().instanceOf(PlayJongo.class);`

I hope this is the right method ;-)

**Comment by morellik** [comment]
I know that the previous solution will not works on Play 2.6. I'll have to use injection that for the moment doesn't work for me. Any suggestion will be appreciated.

**Comment by magro** [comment]
I suspect that the static in `@Inject public static PlayJongo jongo;` is the issue. Does it work without `static`?

**Comment by morellik** [comment]
I tried to remove static, but I enter in a loop of static/non-static referenced context errors

This is a part of Users model
```
public class Users {

    @Inject
    public  PlayJongo jongo;
    public  MongoCollection users() {
         return jongo.jongo().getCollection("DocBox.users");
    }

   public  Users findByEmail(String email) {
        return users().findOne("{email: #}", email).as(Users.class);
    }

        return null;
    }
```

Where I try to call 
`Users ut = Users.findByEmail(requestData.get("email"));`
I have _non-static method findById(java.lang.String) cannot be referenced from a static context_ exception.

If I want to use findByEmail, I've to create an instance of Users, is this correct way to use it?
Because I've lot of methods that creates or update records and I instance Users only for creation whereas I update a record I create an Users object from a query like below:

```
if (method.equals("N")) {
            u = new Users();
        } else {
            u = Users.findById(requestData.get("vid"));
        }
   u.setFirstname(requestData.get("firstname").trim());
   u.setLastname(requestData.get("lastname").trim());
```
If I've to create an instance also for the query, I've to rewrite all methods and at the end the code is not clear, I think.
What do you think?

**Comment by morellik** [comment]
In the play-framework group a member suggested me two possible solutions that I didn't understand:

> 
> 1) Bind the Users class, and @Inject it
> 2) @Inject play.inject.Injector into a managed object, and call injector.instanceOf(Users.class)
> 
> I usually pick #1 myself.

if you understand what it's about, please explain me.

**Comment by magro** [comment]
This is a question for stackoverflow or the mailing list, not jongo specific. You should read and understand dependency injection. Short version: don't use static at all, everything should be injected.

**Comment by morellik** [comment]
The injection apparently could be easy to use. I use it to access to the Play configuration, but in this case is not so easy. 
I tried to inject Users to a controller, but now I've a unMarshall Exception:
```

public class User extends Controller {

    @Inject
    public Users users;
    ...
    Users user = users.authenticate(email, password);
```

Caused by: org.jongo.marshall.MarshallingException: Unable to unmarshall result to class models.Users from content { "_id" : { "$oid" : "5835808af7a573256d85ec8e"} , "firstname" : "Enrico" , "lastname" : "Morelli" , "email" : "morelli@cerm.unifi.it" , "password" : "$2a$10$vnINxQPsDfM.HpOSr0ZAv.8aQXiOn8UqpPA1IV2k26/x1SW9aqEGS" , "role" : "ADMIN"}
	at org.jongo.marshall.jackson.JacksonEngine.unmarshall(JacksonEngine.java:50)
	at org.jongo.ResultHandlerFactory$UnmarshallingResultHandler.map(ResultHandlerFactory.java:43)
	at org.jongo.FindOne.map(FindOne.java:51)
	at org.jongo.FindOne.as(FindOne.java:46)
	at models.Users.authenticate(Users.java:107)
	at controllers.HomeController.authenticate(HomeController.java:65)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$7$$anonfun$apply$7.apply(Routes.scala:405)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$7$$anonfun$apply$7.apply(Routes.scala:405)
	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:157)
	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:156)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not find a (Map) Key deserializer for type [collection type; class java.util.List, contains [simple type, class java.lang.String]]

**Comment by morellik** [comment]
The same error now occurs if I put
```
public class Users  {
 @Inject
    private PlayJongo jongo;
    private MongoCollection users() {
        return jongo.getCollection("DocBox.users");
    }
```

**Comment by morellik** [comment]
I'm frustrated, I ask to play-framework group list, to stackoverflow, here, no one is able to explain how to inject play-jongo 
After having spent the whole week doing tests, I really don't know where head-banging.

**Comment by ShahBinoy** [comment]
Play 2.5 onwards, its all Dependency Injection using Guice. So mark  your `Users` class as singleton

The code below works for me
```
@Singleton
@SuppressWarnings({"unchecked", "rawtypes"})
public class ProfileCRUDService {
   private final MongoCollection     profileCollection;
    @Inject
    public ProfileCRUDService(PlayJongo playJongo, ProjectionContainer projectionContainer) {
        profileCollection = playJongo.getCollection("profile");
    }
}
```

**Comment by morellik** [comment]
Thanks, I tried:

```
@Singleton
@SuppressWarnings({"unchecked", "rawtypes"})
public class Users  {
    private final MongoCollection users;
    @Inject
    public Users(PlayJongo playJongo) {
        users = playJongo.getCollection("DocBox.users");
    }
```

but when I try to execute a query:

```
public Users authenticate(String email, String password) {
        Users user = users.findOne("{email: #}", email).as(Users.class);
        if (user != null) {
            if (HomeController.checkPassword(password, user.password)) {
                return user;
            }
        }

        return null;
    }
```

I receive the same unmarshall error. 
What is your ProjectionContainer? How use Users in a controller, importing or injecting?

**Comment by morellik** [comment]
I am sure to be close to the solution, but I still lack some detail. Until now I had some controllers and some models. Until now my Users model was like that:

```
public class Users {
    public static PlayJongo jongo = Play.current().injector().instanceOf(PlayJongo.class);
    public static MongoCollection users() {
        return jongo.getCollection("DocBox.users");
    }
    private ObjectId _id;
    private String firstname;
    private String lastname;
    private String email;
    private String password;
    private String role;
   ... Getters and setters
   public static Users authenticate(String email, String password) {
        Users user = users().findOne("{email: #}", email).as(Users.class);
        if (user != null) {
            if (HomeController.checkPassword(password, user.password)) {
                return user;
            }
        }
        return null;
    }
    ... Other methods
```

And in my controller in was able to import Users and call all its static methods:
```
import models.Users;
... other imports
public class HomeController extends Controller {
     public  Result authenticate() throws NoSuchAlgorithmException, UnsupportedEncodingException {
        DynamicForm requestData = Form.form().bindFromRequest();
        String email = requestData.get("email").trim();
        String password = requestData.get("password").trim();
        Users user = Users.authenticate(email, password);
        if (user == null) {
            flash("danger", "Incorrect email or password.");
            return redirect(routes.HomeController.login());
        }
  }
 --- other methods
```
To save new users I used 
```
Users u = new Users();
u.setFirstname("Pippo");
u.setLastname("Pollo");
... etc.
Users.users().save(u);
```
I think that using injection I'll cannot use the same instruction (what I'll have to use?). And I think that to use injection I need to write some other peace of software between Models and Controllers (I don't know what).

**Comment by ShahBinoy** [comment]
Can you please provide link on what Greg Methvin helped you?

**Comment by morellik** [comment]
https://groups.google.com/forum/#!topic/play-framework/clKE_uGUnXg

Thanks
