### ISSUE TITLE
RuntimeException

### ISSUE THREAD

**Issue by morellik** [alexanderjarvis/play-jongo#60]
When I start an application I receive:

[ESC[31merrorESC[0m] application - RuntimeException
java.lang.RuntimeException: There is no started application
        at scala.sys.package$.error(package.scala:27)
        at play.api.Play$$anonfun$current$1.apply(Play.scala:86)
        at play.api.Play$$anonfun$current$1.apply(Play.scala:86)
        at scala.Option.getOrElse(Option.scala:121)
        at play.api.Play$.current(Play.scala:86)
        at play.api.Play.current(Play.scala)
        at play.Play.privateCurrent(Play.java:89)
        at play.Play.application(Play.java:22)
        at uk.co.panaxiom.playjongo.PlayJongo.getInstance(PlayJongo.java:103)
        at uk.co.panaxiom.playjongo.PlayJongo.forceNewInstance(PlayJongo.java:115)

The application seems to works fine, but I don't know if I've to worry about it or not.

**Comment by magro** [comment]
Please check that you're using the correct play-jongo version for your playframework version.

**Comment by morellik** [comment]
You are right. I worked with an old version of play.jongo. Now I've downloaded the last master version.
